### ISSUE TITLE
login.php not found and questions

### ISSUE THREAD

**Issue by 007revad** [wallacebrf/Youtube-DL_DLP_Web_Interface_Page#1]
Does this still work in 2024? Does it work on a Synology?

I had to change: 
`$use_sessions=true;`

to:
`$use_sessions=false;`

to get the page to open because it was looking for `https://oscar-youtube/youtube/login.php` which resulted in "File not found."

Now that page opens it has the following error at the top:
`Warning: include(/volume1/web/functions.php): Failed to open stream: No such file or directory in /volume1/web/youtube/youtube-dlp.php on line 33 Warning: include(): Failed opening '/volume1/web/functions.php' for inclusion (include_path='.:/usr/share/pear') in /volume1/web/youtube/youtube-dlp.php on line 33`

I can't see where `/usr/share/pear` is coming from?

Clicking on "Display Youtube-dlp Version" results in the "File not found" error and the URL changes to: 
`https://oscar-youtube/youtube/index.php?page=13`

**Comment by wallacebrf** [comment]
yes, this does work. the functions.php file it is looking for is the same one used for the smart scheduler. 

a lot of the github stuff i have all works 100% for me, i was mostly using github to store the code
